### Health
GET http://localhost:8080/api/planning/health

### Solve multipart
POST http://localhost:8080/api/planning/solve
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="soutenance-15.planning"
Content-Type: application/octet-stream

< ./soutenance-15.planning
--boundary--

### Solve JSON body
POST http://localhost:8080/api/planning/solve-json
Content-Type: application/json

< ./soutenance-15.planning
